server.port: 7002
springdoc:
  swagger-ui:
    enabled: true
    operations-sorter: method
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/trash
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: localhost:6379
    port: 6379
    password: root
office:
  url: localhost:8080
aws:
  ses:
    access-key: AKIARK3V5NVAE2M3WUZN
    secret-key: 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
    region: us-east-1
